### ISSUE TITLE
edit URLs in the Hacking ZAP #4 blog post to account for the GitHub migration

### ISSUE THREAD

**Issue by dmitris** [zaproxy/zap-extensions#5]
http://zaproxy.blogspot.de/2014/04/hacking-zap-4-active-scan-rules.html is an important piece of documentation for those interested in hacking on ZAP or looking under the hood, it comes up a lot in search queries and gets mentioned on the zaproxy-develop mailing list.  Would it be possible to edit that post to link to the new URLs on GitHub?  It would help the readers to click directly to the quotes file or directory rather than get redirected to the main project GitHub page.

For example,  the "Beta Quality" link points to https://code.google.com/p/zap-extensions/source/browse/#svn%2Fbranches%2Fbeta%2Fsrc%2Forg%2Fzaproxy%2Fzap%2Fextension%2FascanrulesBeta which redirects to https://github.com/zaproxy/zap-extensions#svn%2Fbranches%2Fbeta%2Fsrc%2Forg%2Fzaproxy%2Fzap%2Fextension%2FascanrulesBeta which the same page as https://github.com/zaproxy/zap-extensions (project main page / README.md).  It should be replaced with:
https://github.com/zaproxy/zap-extensions/tree/beta/src/org/zaproxy/zap/extension/ascanrulesBeta

**Comment by dmitris** [comment]
Another example is the ExampleSimpleActiveScanner link - currently points to 
https://code.google.com/p/zap-extensions/source/browse/branches/alpha/src/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleSimpleActiveScanner.java (which takes you to the main page), would be great to re-target it to https://github.com/zaproxy/zap-extensions/blob/alpha/src/org/zaproxy/zap/extension/ascanrulesAlpha/ExampleSimpleActiveScanner.java to enable a one-step click-through :smile:

**Comment by psiinon** [comment]
Yes, its on my TODO list ;)

**Comment by psiinon** [comment]
Think I've updated all the links - let me know if I've missed any!

**Comment by dmitris** [comment]
Awesome, thanks!

A few very minor things:

> You should periodically check to see if the AbstractPlugin.isStop()
I believe the "isStop()" link should point to https://code.google.com/p/zaproxy/source/browse/trunk/src/org/parosproxy/paros/core/scanner/AbstractPlugin.java#446 instead of https://code.google.com/p/zaproxy/source/browse/trunk/src/org/parosproxy/paros/core/scanner/AbstractPlugin.java#414 (line number)

For the "AbstractAppParamPlugin.scan(HttpMessage msg, NameValuePair originalParam)" it would be
https://code.google.com/p/zaproxy/source/browse/trunk/src/org/parosproxy/paros/core/scanner/AbstractAppParamPlugin.java#223 (instead of the current Line 211 hash anchor in the link)

**Comment by psiinon** [comment]
Updated - many thanks!
